name: env_monitoring
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  intl: ^0.18.0
  uuid: ^3.0.7
  go_router: ^6.5.0
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  dio: ^4.0.6
  shared_preferences: ^2.0.20
  cupertino_icons: ^1.0.5
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  curved_navigation_bar: ^1.0.3
  animations: ^2.0.7
  flutter_email_sender: 5.1.0
  fl_chart: ^0.61.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - temp/
